const ROLES = {
  ADMIN: 'admin',
  PENGURUS_BIDANG_1: 'pengurus-bidang-1',
  SEKRETARIAT: 'sekretariat',
  BENDAHARA: 'bendahara',
  PENULIS_KONTEN: 'penulis-konten',
};

const ADMIN_FULL_ROLES = [
  ROLES.ADMIN,
  ROLES.PENGURUS_BIDANG_1,
];

const ALL_ADMIN_WEB_ROLES = [
  ...ADMIN_FULL_ROLES,
  ROLES.SEKRETARIAT,
  ROLES.BENDAHARA,
  ROLES.PENULIS_KONTEN,
];

const CONTENT_ROLES = [
  ...ADMIN_FULL_ROLES,
  ROLES.PENULIS_KONTEN,
];

const SECRETARIAT_ROLES = [
  ...ADMIN_FULL_ROLES,
  ROLES.SEKRETARIAT,
];

const FINANCE_ROLES = [
  ...ADMIN_FULL_ROLES,
  ROLES.BENDAHARA,
];

const COMMUNICATION_ROLES = [
  ...ADMIN_FULL_ROLES,
  ROLES.SEKRETARIAT,
  ROLES.BENDAHARA,
];

const KEMITRAAN_ROLES = [
  ...ADMIN_FULL_ROLES,
  ROLES.SEKRETARIAT,
  ROLES.BENDAHARA,
];

const BANTUAN_ROLES = ADMIN_FULL_ROLES;

const DANA_BANTUAN_ROLES = FINANCE_ROLES;

const SUBMISSION_ROLES = [
  ...ADMIN_FULL_ROLES,
  ROLES.SEKRETARIAT,
];

module.exports = {
  ROLES,
  ADMIN_FULL_ROLES,
  ALL_ADMIN_WEB_ROLES,
  CONTENT_ROLES,
  SECRETARIAT_ROLES,
  FINANCE_ROLES,
  COMMUNICATION_ROLES,
  KEMITRAAN_ROLES,
  BANTUAN_ROLES,
  DANA_BANTUAN_ROLES,
  SUBMISSION_ROLES,
};
